services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: pira
      POSTGRES_PASSWORD: pirapassword
      POSTGRES_DB: piradb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
